### ISSUE TITLE
UIConfig should be updated when collapsing/expanding all tiles

### ISSUE THREAD

**Issue by Blackbaud-ThomasOrtiz** [blackbaud/skyux-tiles#41]
### Expected behavior
- I should be able to collapse/expand all tiles programmatically and have that new collapse state be reflected when refreshing the page.

### Actual behavior
- When I programmatically set the tile collapse state the new state is not cached.
- The result of this is that when I refresh the page the tiles are not in the same collapsed state as before.

### Steps to reproduce
1. Create a page with multiple tiles, collapse all / expand all buttons, and using the UIConfig
2. Hit the collapse all button 
3. Notice that an API request to the UIConfig service was never made 
4. Refresh the page
5. Notice that the tiles did not retain the state they were in after hitting the collapse all button.

### Ideas
- Some formal way through the tile component to 
  - expand/collapse all tiles
  - trigger a UIConfig service update

### Severity
- High

### Impact
- Expand / Collapse buttons with some form of caching are seen throughout FENXT / RENXT record pages.

**Comment by Blackbaud-TrevorBurch** [comment]
In `3.2.0`
