### ISSUE TITLE
Add ability to add tiles via the message stream.

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-tiles#43]
Today the only way to add a tile to the dashboard after initialization is to use the tile dashboard service method. However, the tile dashboard service was not intended to be public. Now that we have a message stream for the dashboard, we should add the ability to add new tiles through this message stream. 

Note: we should remove the tile dashboard service from our public docs when adding this functionality to the docs.

**Comment by Blackbaud-TrevorBurch** [comment]
Progress indicator passes data with its messages in a similar way to what we will need to do here. https://github.com/blackbaud/skyux-progress-indicator/blob/master/src/app/public/modules/progress-indicator/types/progress-indicator-message.ts#L8-L17

**Comment by Blackbaud-AlexKingman** [comment]
Closing.
To our current knowledge, there isn't any consumer use-case that requires the ability to add tiles after the dashboard is fully rendered. Please reopen if there is still a need for more discussion.
